before:
  hooks:
    - go mod tidy
builds:
  - id: tailpipe-linux-amd64
    binary: tailpipe
    goos:
      - darwin
    goarch:
      - amd64

    env:
      - CC=oa64-clang
      - CXX=oa64-clang++

    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser

archives:
  - id: homebrew
    format: tar.gz
    name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
    files:
      - none*
