before:
  hooks:
    - go mod tidy
builds:
  - id: tailpipe-linux-amd64
    binary: tailpipe
    goos:
      - linux
    goarch:
      - amd64

    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++

    hooks:
      pre:
        - ./scripts/download_json_extension.sh linux amd64

    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser

archives:
  - files:
      - none*
    format: zip
    id: homebrew
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: linux
        format: tar.gz
