version: 2

before:
  hooks:
    - go mod tidy

builds:
  # Linux AMD64 build with GCC 13+
  - id: tailpipe-linux-amd64
    binary: tailpipe
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc-13
      - CXX=x86_64-linux-gnu-g++-13
      - CGO_CXXFLAGS=-std=c++17
      - CGO_LDFLAGS=-lstdc++ -static-libstdc++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser
    flags:
      - -buildvcs=false

  # Linux ARM64 build with GCC 13+
  - id: tailpipe-linux-arm64
    binary: tailpipe
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc-13
      - CXX=aarch64-linux-gnu-g++-13
      - CGO_CXXFLAGS=-std=c++17
      - CGO_LDFLAGS=-lstdc++ -static-libstdc++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser
    flags:
      - -buildvcs=false

release:
  prerelease: auto

archives:
  - id: homebrew
    format: tar.gz
    name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - ids:
      - homebrew
    name: tailpipe@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    repository:
      owner: turbot
      name: homebrew-tap
      branch: tailpipe-brew
    directory: Formula
    url_template: "https://github.com/turbot/tailpipe/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://tailpipe.io/"
    description: "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
    skip_upload: auto
    install: |-
      bin.install "tailpipe"