name: "Sysroot Build Test"

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths: [ 'Dockerfile.sysroot', 'Makefile' ]

jobs:
  build-sysroot:
    name: Build Sysroot and Test Build
    runs-on: ubuntu-latest  # This is x86_64, so sysroot will work perfectly
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Sysroot
        run: |
          docker build -f Dockerfile.sysroot -t tailpipe-sysroot:bookworm .
          docker create --name temp-sysroot tailpipe-sysroot:bookworm
          docker cp temp-sysroot:/sysroot ./sysroot
          docker rm temp-sysroot
          
      - name: Verify Sysroot Contents
        run: |
          echo "=== Sysroot Structure ==="
          find sysroot/ -type f -name "libstdc++*" | head -10
          echo "=== AMD64 Libraries ==="
          find sysroot/ -name "*x86_64*" -o -name "*amd64*" | head -10
          
      - name: Test Release Build
        run: |
          make release-acceptance
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tailpipe-binaries
          path: dist/
          if-no-files-found: error
